USE master;
IF DB_ID(N'TMT') IS NOT NULL DROP DATABASE TMT
CREATE DATABASE TMT;
GO
USE TMT;
GO
CREATE SCHEMA Sales AUTHORIZATION dbo;
GO
CREATE SCHEMA Theaters AUTHORIZATION dbo;
GO

CREATE TABLE Sales.Account
(
	AccountId INT NOT NULL IDENTITY,
	FirstName NVARCHAR(100) NOT NULL, 
	LastName NVARCHAR(100) NOT NULL, 
	NickName NVARCHAR(100) NOT NULL, 
	Email NVARCHAR(1000) NOT NULL, 
	Phone NVARCHAR(100) NOT NULL,
	ViewedMovie NVARCHAR(1000) NOT NULL,
	WatchList NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_Account PRIMARY KEY(AccountId)
);

CREATE TABLE Theaters.Room
(
	RoomId INT NOT NULL IDENTITY,
	RoomNumber INT NOT NULL,
	RoomName NVARCHAR(500) NOT NULL,
	TotalSeat INT NOT NULL, 
	AudioSystem NVARCHAR(1000) NOT NULL,
	CONSTRAINT PK_Room PRIMARY KEY(RoomId)
);

CREATE TABLE Sales.Ticket
(
	TicketId INT NOT NULL IDENTITY,
	RoomId INT NOT NULL,
	MovieTitle NVARCHAR(1000), 
	Price MONEY NOT NULL, 
	SaleDate DATE NOT NULL, 
	ShowTime TIME NOT NULL,
	Seat INT NOT NULL,
	CONSTRAINT PK_Ticket PRIMARY KEY(TicketId),
	CONSTRAINT FK_Ticket_Room FOREIGN KEY(RoomId) REFERENCES Theaters.Room(RoomId)
);

CREATE TABLE Sales.Merchandise
(
	MerchandiseId INT NOT NULL IDENTITY,
	Photo BIT NOT NULL,
	FoodName NVARCHAR(1000) NOT NULL, 
	SouvenirName NVARCHAR(1000) NOT NULL, 
	Price MONEY NOT NULL,
	CONSTRAINT PK_Merchandise PRIMARY KEY(MerchandiseId)
);


CREATE TABLE Sales.Receipt
(
	ReceiptId INT NOT NULL IDENTITY,
	AccountId INT NOT NULL, 
	TicketId INT NOT NULL,
	Email NVARCHAR(1000) NOT NULL, 
	Reminder NVARCHAR(1000) NOT NULL,
	CONSTRAINT PK_Receipt PRIMARY KEY(ReceiptId),
	CONSTRAINT FK_Receipt_Account FOREIGN KEY(AccountId) REFERENCES Sales.Account(AccountId),
	CONSTRAINT FK_Receipt_Ticket FOREIGN KEY(TicketId) REFERENCES Sales.Ticket(TicketId)

);



CREATE TABLE Theaters.Movie
(
	MovieId INT NOT NULL IDENTITY,
	RoomId INT NOT NULL,
	Title NVARCHAR(1000) NOT NULL,
	ReleaseDate DATE NOT NULL, 
	AgeRating NVARCHAR(100) NOT NULL, 
	Genre NVARCHAR(100) NOT NULL,
	ShowDate DATE NOT NULL, 
	ShowTime TIME NOT NULL,
	Runtime NVARCHAR(100) NOT NULL,
	CountryOrigin NVARCHAR(1000) NOT NULL,
	MovieLanguage NVARCHAR(1000) NOT NULL,
	ProductionCo NVARCHAR(100) NOT NULL, 
	Storyline NVARCHAR(1000) NOT NULL,
	Review NVARCHAR(1000) NOT NULL,
	CONSTRAINT PK_Movie PRIMARY KEY(MovieId),
	CONSTRAINT FK_Movie_Room FOREIGN KEY(RoomId) REFERENCES Theaters.Room(RoomId)
);

CREATE TABLE Theaters.List
(
	ListId INT NOT NULL IDENTITY,
	AccountId INT NOT NULL,
	MovieId INT NOT NULL,
	ShowTime TIME NOT NULL, 
	Theater NVARCHAR(500) NOT NULL, 
	CONSTRAINT PK_List PRIMARY KEY(ListId),
	CONSTRAINT FK_List_Account FOREIGN KEY(AccountId) REFERENCES Sales.Account(AccountId),
	CONSTRAINT FK_List_Movie FOREIGN KEY(MovieId) REFERENCES Theaters.Movie(MovieId)
);


CREATE TABLE Theaters.Review
(
	ReviewId INT NOT NULL IDENTITY,
	MovieId INT NOT NULL, 
	ListId INT NOT NULL,
	StarRating INT NOT NULL, 
	Comment NVARCHAR(1000) NOT NULL, 
	ReviewDate DATETIME2 NOT NULL, 
	Total INT NOT NULL,
	CONSTRAINT PK_Review PRIMARY KEY(ReviewId),
	CONSTRAINT FK_Review_Movie FOREIGN KEY(MovieId) REFERENCES Theaters.Movie(MovieId),
	CONSTRAINT FK_Review_List FOREIGN KEY(ListId) REFERENCES Theaters.List(ListId)

);


CREATE TABLE Theaters.MovieCrew
(
	MovieCrewId INT NOT NULL IDENTITY,
	MovieId INT NOT NULL,
	CastMember NVARCHAR(1000) NOT NULL,
	CharacterName NVARCHAR(1000) NOT NULL,
	RoleName NVARCHAR(1000) NOT NULL,
	DOB DATE NOT NULL, 
	HomeCity NVARCHAR(1000) NOT NULL,
	HomeState NVARCHAR(1000) NOT NULL,
	Country NVARCHAR(1000) NOT NULL,
	CONSTRAINT PK_MovieCrew PRIMARY KEY(MovieCrewId),
	CONSTRAINT FK_MovieCrew_Movie FOREIGN KEY(MovieId) REFERENCES Theaters.Movie(MovieId)
);

